### ISSUE TITLE
Add a default timeout in demoji.download_codes()

### ISSUE THREAD

**Issue by Ak4zh** [bsolomon1124/demoji#27]
**Describe the bug**
demoji.download_codes() has no inbuilt timeout and it gets stuck for a very long time if something is wrong.
I had this line at start of my app with a try except but it does not raises exception rather just gets stuck resulting in nginx timeout of my web app and the loop continues.

**To Reproduce**
```python
    import demoji
    try:
        demoji.download_codes()
    except Exception:
        pass
```

**Expected behavior**
It should download or timeout and raise Exception but since requests default timeout is None it keeps stuck

**Comment by bsolomon1124** [comment]
@Ak4zh 

@bennyhawk 

This issue has been tentatively resolved by demoji release 1.0.0, which is in release candidate stage right now.
This release bundles static copy of Unicode emoji data with the package rather than requiring a runtime download.

You can get this pre-release using `--pre`:

```
python3 -m pip install --pre -U demoji
```

I appreciate your feedback prior to releasing 1.0.0!
