### ISSUE TITLE
Ability to cache emoji data in a user defined directory

### ISSUE THREAD

**Issue by bennyhawk** [bsolomon1124/demoji#28]
**Is your feature request related to a problem? Please describe.**
Yes. AWS Lambda provides the application ephermal storage space only on /tmp directory. When implementing demoji on AWS Lambda, we get a permission issue when caching the emoji data

**Describe the solution you'd like**
Ability to specify a directory when caching the emoji data. Possibly in the download codes function

**Describe alternatives you've considered**
I do not see any other alternative

**Comment by bsolomon1124** [comment]
@bennyhawk 

This issue has been tentatively resolved by demoji release 1.0.0, which is in release candidate stage right now.
This release bundles static copy of Unicode emoji data with the package rather than requiring a runtime download.

You can get this pre-release using `--pre`:

```
python3 -m pip install --pre -U demoji
```

I appreciate your feedback prior to releasing 1.0.0!
