### ISSUE TITLE
unicode.org connection refused

### ISSUE THREAD

**Issue by quimdt** [bsolomon1124/demoji#4]
**Describe the bug**
unicode.org connection refused. When try to download emojis codes. Rise exception connection refused.
Seams that unicode.org change the web to https://home.unicode.org
And the https://home.unicode.org/Public/emoji/12.0/emoji-test.txt does not exists anymore

**To Reproduce**
1. try to download using command demoji.download_codes()

**Comment by frostace** [comment]
same issue here, looking forward to some solution

**Comment by bsolomon1124** [comment]
This could be a difference in underlying settings, but I am able to access http://unicode.org/Public/emoji/12.0/emoji-test.txt just fine.

Are you able to access http://unicode.org/Public/emoji/12.0/emoji-test.txt in a browser @quimdt @frostace ?

**Comment by quimdt** [comment]
@bsolomon1124 Yes I can access.
It seams that some times the page is down and cause the error of connection.

**Comment by bsolomon1124** [comment]
Okay, sorry for the trouble @quimdt . I do realize that page doesn't seem to be an 'official' database and it's possibly been replaced by a different more canonical URL.  I'll work on finding an alternate and please let me know if you find something.

**Comment by bsolomon1124** [comment]
@quimdt 

@bennyhawk 

This issue has been tentatively resolved by demoji release 1.0.0, which is in release candidate stage right now.
This release bundles static copy of Unicode emoji data with the package rather than requiring a runtime download.

You can get this pre-release using `--pre`:

```
python3 -m pip install --pre -U demoji
```

I appreciate your feedback prior to releasing 1.0.0!
